"""initial tables

Revision ID: 39739ba005ac
Revises: eaff54b6503c
Create Date: 2026-05-05 12:52:56.225517

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '39739ba005ac'
down_revision: Union[str, None] = 'eaff54b6503c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
