"""initial tables

Revision ID: 5f722ff4d809
Revises: d4f5a6b7c8d9
Create Date: 2026-05-10 12:33:55.349087

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5f722ff4d809'
down_revision: Union[str, None] = 'd4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subjects', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('classes', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
